export const errorX = " You should write x between -3 and 3 ";
export const noError = "no-warning";
export const warning = "warning";
export const normal = "normal";
export const error = "error";
export const active = "active";
export const noActive = "no-active";
export const x = "x";
export const y = "y";
export const R = "R";
export const send = "send";
export const logX = "log_x";
export const logY = "log_y";
export const change = "change";
export const errorY = " You should choose one y ";
export const withOutError = "";
export const connectionError = "Please check your connection to the internet"
export const div = "div";
export const classNew = "new";
export const row = "row";
export const headTable = "head_table";
export const click = "click";
export const reach = 'reach';
export const miss = 'miss';

